import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const STYLE_PROMPTS: Record<string, string> = {
  realistic: "Transform this food product into a professional studio photograph with realistic studio lighting, clean neutral background, high detail, sharp focus, appetizing presentation, commercial food photography style.",
  premium: "Transform this food product into a luxury premium photograph with elegant golden warm lighting, sophisticated dark background, high-end restaurant presentation, fine dining aesthetic, professional food styling.",
  animated: "Transform this food product into a colorful illustrated cartoon style, fun vibrant colors, playful presentation, appealing to all ages, digital art style, clean vector-like illustration.",
  minimalist: "Transform this food product into a minimalist photograph with soft natural shadows, neutral muted tones, clean aesthetic, modern Scandinavian style, simple elegant composition.",
  white_bg: "Transform this food product into a pure white background e-commerce style photo, studio product shot, clean professional presentation, no shadows, isolated product, online store ready.",
  dark_mode: "Transform this food product into a dark moody photograph with dramatic lighting, dark elegant background, professional food photography, high contrast, premium feel.",
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { imageUrl, style, menuItemId, menuItemName, storeId } = await req.json();

    console.log(`Processing image enhancement for item: ${menuItemName}, style: ${style}`);

    if (!imageUrl || !style || !storeId) {
      return new Response(
        JSON.stringify({ error: 'Missing required parameters' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      console.error('LOVABLE_API_KEY is not configured');
      return new Response(
        JSON.stringify({ error: 'AI service not configured' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const prompt = STYLE_PROMPTS[style] || STYLE_PROMPTS.realistic;
    const fullPrompt = `${prompt} Product name: ${menuItemName}. Keep the food item recognizable but enhance its presentation.`;

    console.log(`Using prompt: ${fullPrompt.substring(0, 100)}...`);

    // Call Lovable AI Gateway for image editing
    const aiResponse = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash-image-preview',
        messages: [
          {
            role: 'user',
            content: [
              {
                type: 'text',
                text: fullPrompt,
              },
              {
                type: 'image_url',
                image_url: {
                  url: imageUrl,
                },
              },
            ],
          },
        ],
        modalities: ['image', 'text'],
      }),
    });

    if (!aiResponse.ok) {
      const errorText = await aiResponse.text();
      console.error('AI Gateway error:', aiResponse.status, errorText);
      
      if (aiResponse.status === 429) {
        return new Response(
          JSON.stringify({ error: 'Rate limit exceeded', status: 429 }),
          { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
      if (aiResponse.status === 402) {
        return new Response(
          JSON.stringify({ error: 'Payment required', status: 402 }),
          { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
      
      return new Response(
        JSON.stringify({ error: 'Failed to process image with AI' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const aiData = await aiResponse.json();
    console.log('AI response received');

    // Extract the generated image
    const generatedImageUrl = aiData.choices?.[0]?.message?.images?.[0]?.image_url?.url;
    
    if (!generatedImageUrl) {
      console.error('No image in AI response:', JSON.stringify(aiData).substring(0, 500));
      return new Response(
        JSON.stringify({ error: 'No image generated by AI' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Initialize Supabase client
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Upload the base64 image to storage
    const base64Data = generatedImageUrl.replace(/^data:image\/\w+;base64,/, '');
    const imageBuffer = Uint8Array.from(atob(base64Data), c => c.charCodeAt(0));
    
    const fileName = `ai-enhanced/${storeId}/${menuItemId}-${style}-${Date.now()}.png`;
    
    const { data: uploadData, error: uploadError } = await supabase.storage
      .from('menu-images')
      .upload(fileName, imageBuffer, {
        contentType: 'image/png',
        upsert: true,
      });

    if (uploadError) {
      console.error('Storage upload error:', uploadError);
      return new Response(
        JSON.stringify({ error: 'Failed to save enhanced image' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Get public URL
    const { data: { publicUrl } } = supabase.storage
      .from('menu-images')
      .getPublicUrl(fileName);

    console.log('Enhanced image uploaded:', publicUrl);

    // Record in history
    await supabase.from('ai_enhancement_history').insert({
      store_id: storeId,
      menu_item_id: menuItemId,
      original_image_url: imageUrl,
      enhanced_image_url: publicUrl,
      style: style,
      prompt_used: fullPrompt,
      credit_type: 'monthly',
    });

    return new Response(
      JSON.stringify({ 
        success: true,
        enhancedImageUrl: publicUrl,
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Error in enhance-product-image:', error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : 'Unknown error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
